// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCollection.Models;

namespace MovieCollection.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    [Migration("20220127052744_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("MovieCollection.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Sport/Drama",
                            Director = "Boaz Yakin",
                            Edited = false,
                            LentTo = "",
                            Notes = "One of Conner's Favs",
                            Rating = "PG",
                            Title = "Remember the Titans",
                            Year = (short)2000
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Musical/Drama",
                            Director = "Michael Gracey",
                            Edited = false,
                            LentTo = "",
                            Notes = "One of Conner's Favs",
                            Rating = "PG",
                            Title = "Greatest Showman, The",
                            Year = (short)2017
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Family/Adventure",
                            Director = "Dan Scanlon",
                            Edited = false,
                            LentTo = "",
                            Notes = "One of Conner's Favs",
                            Rating = "PG",
                            Title = "Onward",
                            Year = (short)2000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
